import { createClient } from './supabase-lite.js';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, APP_VERSION } from './config.js';
import { setupUpdates } from './update.js';
import { setupInstall } from './install.js';

const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null, profile=null;
let alertsRequest=null,adminRequest=null,accessCheck=null,lastAccessCheck=0;
let refreshFeedbackTimer=null;
let currentView='feed',navigationReady=false;
const viewScroll={feed:0,create:0,admin:0};
const VIEWS=['feed','create','admin'];
const canCreate=()=>['creator','admin'].includes(profile?.role), canApprove=()=>['approver','admin'].includes(profile?.role), isAdmin=()=>profile?.role==='admin';
const ALERT_COLUMNS='id,title,status,photo_url,child_name,age,description,last_known,vehicle,law_agency,law_phone,created_at';
const USER_PAGE_SIZE=25;
const userDirectory={search:'',role:'all',status:'all',cursor:null,loaded:0,total:0,busy:false,timer:null};

setupUpdates();
setupInstall();
if('scrollRestoration'in history)history.scrollRestoration='manual';
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(console.warn);

function note(msg){const el=$('#auth-note');el.textContent=msg;el.classList.remove('hidden')}
function clearNote(){$('#auth-note').classList.add('hidden')}
function setAuthMode(mode){const login=mode==='login';$('#login-form').classList.toggle('hidden',!login);$('#signup-form').classList.toggle('hidden',login);$('#auth-login-tab').className=login?'maroon':'ghost';$('#auth-signup-tab').className=login?'ghost':'maroon';clearNote()}
async function signInGoogle(){clearNote();const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)note(error.message)}
async function signInEmail(e){e.preventDefault();clearNote();const f=new FormData(e.currentTarget);const email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');const {error}=await db.auth.signInWithPassword({email,password});if(error)return note('Email/password sign-in failed. Check your email and password. If this address was originally registered with Google, use Continue with Google.');location.reload()}
async function signUpEmail(e){e.preventDefault();clearNote();const form=e.currentTarget,submit=form.querySelector('button[type="submit"]'),originalText=submit?.textContent;const f=new FormData(form);const full_name=String(f.get('full_name')||'').trim(),email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');if(full_name.length<2)return note('Please enter your full name.');if(password.length<10)return note('Use a password with at least 10 characters.');if(submit){submit.disabled=true;submit.textContent='Creating account…'}try{const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name}}});if(error){if(/already registered/i.test(error.message))return note('An account already exists with this email. Please sign in instead, or use Continue with Google if that is how the account was created.');return note(`Account could not be created: ${error.message}`)}if(data.session){note('Account created successfully. Signing you in…');setTimeout(()=>location.reload(),500);return}note('Account request completed, but no sign-in session was returned. Please try signing in.');setAuthMode('login');}finally{if(submit){submit.disabled=false;submit.textContent=originalText||'Create account'}}}
async function forgotPassword(){clearNote();const email=String(new FormData($('#login-form')).get('email')||'').trim();if(!email)return note('Enter your email address first.');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)return note(error.message);note('Password reset request received. Check your inbox and spam folder.')}
async function signOut(){await db.auth.signOut();location.reload()}
async function loadProfile(){const {data,error}=await db.from('profiles').select('id,full_name,role,is_active,access_status').eq('id',user.id).single();if(error)throw error;profile=data;}
function paintIdentity(){const meta=user.user_metadata||{};$('#who-name').textContent=profile.full_name||meta.full_name||meta.name||'Signed in';$('#who-email').textContent=user.email||'';$('#who-role').textContent=profile.role;$('#who').classList.remove('hidden');$('#tab-create').classList.toggle('hidden',!canCreate());$('#tab-admin').classList.toggle('hidden',!(canApprove()||isAdmin()));if(canApprove()){$('#create-help').textContent='As an authorized admin or approver, this sends the alert immediately and notifies subscribed phones.';$('#alert-submit').textContent='Send alert now'}else{$('#create-help').textContent='Your request will stay pending until an approver or admin activates it.';$('#alert-submit').textContent='Submit for approval'}}
function showAccessState(){const pending=profile.access_status==='pending';$('#auth').classList.add('hidden');$('#app').classList.add('hidden');$('#access-state').classList.remove('hidden');$('#access-state-title').textContent=pending?'Awaiting administrator approval':'Access denied';$('#access-state-copy').textContent=pending?'Your account was created successfully. An administrator still needs to approve it before you can view community alerts.':'An administrator denied or revoked access for this account. Contact the district if you believe this was a mistake.';$('#decision-notify-wrap').classList.toggle('hidden',!pending);history.replaceState({view:'status'},'','#status');if(pending)paintNotificationToggle().catch(error=>console.warn(error.message));}
function allowedViews(){return VIEWS.filter(name=>name==='feed'||(name==='create'&&canCreate())||(name==='admin'&&(canApprove()||isAdmin())))}
function routeView(){const requested=location.hash.slice(1).toLowerCase();return allowedViews().includes(requested)?requested:'feed'}
function viewTop(){const tabs=$('.tabs'),header=document.querySelector('header');return Math.max(0,tabs.offsetTop-(header?.offsetHeight||0)-8)}
function setView(name,{historyMode='push',restoreScroll=false}={}){const destination=allowedViews().includes(name)?name:'feed',changed=destination!==currentView;if(navigationReady&&changed)viewScroll[currentView]=scrollY;currentView=destination;for(const viewName of VIEWS){const selected=viewName===destination,panel=$('#'+viewName),button=$('#tab-'+viewName);panel.classList.toggle('hidden',!selected);panel.setAttribute('aria-hidden',String(!selected));button?.classList.toggle('on',selected);button?.setAttribute('aria-selected',String(selected));if(button)button.tabIndex=selected?0:-1}const hash=`#${destination}`;if(historyMode==='push'&&location.hash!==hash)history.pushState({view:destination},'',hash);else if(historyMode==='replace'&&location.hash!==hash)history.replaceState({view:destination},'',hash);if(changed){const panel=$('#'+destination);panel.classList.remove('view-enter');requestAnimationFrame(()=>panel.classList.add('view-enter'));if(navigationReady)requestAnimationFrame(()=>scrollTo({top:restoreScroll?(viewScroll[destination]||viewTop()):viewTop(),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}))}if(destination==='admin')loadAdmin().catch(e=>alert(e.message));}
function moveTabFocus(direction){const views=allowedViews(),index=views.indexOf(currentView),next=views[(index+direction+views.length)%views.length];$('#tab-'+next)?.focus();setView(next)}
function statusClass(s){return ['active','located'].includes(s)?'active':s==='pending'?'pending':'closed'}
function safeImageUrl(value){try{const url=new URL(value,location.href);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return ''}}
function bytesFromBase64(value){const padded=value+'='.repeat((4-value.length%4)%4),raw=atob(padded.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function isIOSDevice(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function isStandaloneApp(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function pushCapability(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))return{supported:false,reason:'Notifications are not supported in this browser. On iPhone, open the latest app link in Safari and add it to the Home Screen first.'};if(isIOSDevice()&&!isStandaloneApp())return{supported:false,reason:'For iPhone notifications: open the latest app link in Safari, tap Share, choose Add to Home Screen, keep Open as Web App turned on, then open the new app icon.'};return{supported:true}}
async function edgeError(error,fallback){try{const detail=await error?.context?.json();return detail?.error||detail?.message||error?.message||fallback}catch{return error?.message||fallback}}
async function notificationCall(action,body={}){const {data,error}=await db.functions.invoke('alert-notifications',{body:{action,...body}});if(error)throw new Error(await edgeError(error,'Notification service is unavailable.'));if(!data?.ok)throw new Error(data?.error||'Notification request failed.');return data}
async function currentPushSubscription(){if(!('serviceWorker'in navigator))return null;const registration=await navigator.serviceWorker.ready;return registration.pushManager?.getSubscription()||null}
function deviceLabel(){if(/iPad|iPhone|iPod/.test(navigator.userAgent))return'iPhone / iPad';if(/Android/.test(navigator.userAgent))return'Android phone';return'Web browser'}
function notificationElements(){const waiting=profile?.access_status==='pending';return{button:$(waiting?'#decision-notify-toggle':'#notify-toggle'),status:$(waiting?'#decision-notify-status':'#notify-status'),waiting}}
async function paintNotificationToggle(){const {button,status,waiting}=notificationElements();if(!button)return;const capability=pushCapability();if(!capability.supported){button.disabled=true;button.textContent='Notifications unavailable';status.textContent=capability.reason;return}button.disabled=false;if(Notification.permission==='denied'){button.dataset.enabled='blocked';button.textContent='Fix notifications';button.classList.remove('notify-on');status.textContent=isIOSDevice()?'Notifications are blocked on this iPhone. Open Settings, Notifications, BSD7 Assist, then turn on Allow Notifications. If BSD7 Assist is missing, delete the Home Screen icon and add the app again from Safari.':'Notifications are blocked. Open your browser or device notification settings and allow this app.';return}const subscription=await currentPushSubscription();let enabled=false;if(subscription){try{enabled=(await notificationCall('status',{endpoint:subscription.endpoint})).enabled}catch{enabled=true}}button.dataset.enabled=enabled?'1':'0';button.textContent=enabled?'Notifications on':waiting?'Notify me of the decision':'Enable notifications';button.classList.toggle('notify-on',enabled);status.textContent=enabled?(waiting?'We will notify this device when an administrator decides.':'Alerts will reach this device even when the app is closed.'):''}
async function toggleNotifications(){const {button}=notificationElements();if(button.disabled)return;button.disabled=true;const turningOn=button.dataset.enabled!=='1';try{if(turningOn){const capability=pushCapability();if(!capability.supported)throw new Error(capability.reason);const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(permission!=='granted')throw new Error(isIOSDevice()?'Notifications are still off. Open iPhone Settings, tap Notifications, choose BSD7 Assist, and allow notifications. If BSD7 Assist is not listed, remove the Home Screen icon and add it again from Safari.':'Notifications are still off. Open your browser or system notification settings and allow notifications for this app.');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription(),created=false;if(!subscription){const config=await notificationCall('config');subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytesFromBase64(config.publicKey)});created=true}try{const json=subscription.toJSON();await notificationCall('subscribe',{endpoint:json.endpoint,p256dh:json.keys?.p256dh,auth:json.keys?.auth,deviceLabel:deviceLabel(),userAgent:navigator.userAgent})}catch(error){if(created)await subscription.unsubscribe().catch(()=>{});throw error}}else{const subscription=await currentPushSubscription();if(subscription){await notificationCall('unsubscribe',{endpoint:subscription.endpoint});await subscription.unsubscribe()}}await paintNotificationToggle()}catch(error){alert(error.message);button.disabled=false}}
async function resetPhoneSetup(){if(!confirm('This will clear the saved app copy on this phone and sign this device out. Then delete the Home Screen icon and add it again from Safari. Continue?'))return;try{await db.auth.signOut({scope:'local'}).catch(()=>{});if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister().catch(()=>{})))}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith('bsd7-community-')).map(key=>caches.delete(key)))}localStorage.clear();sessionStorage.clear();alert('Phone setup was reset. Delete the Home Screen icon, open the latest link in Safari, add it to Home Screen with Open as Web App on, then enable notifications again.')}finally{location.replace(`${location.pathname}?fresh=${Date.now()}`)}}
async function sendAlertNotification(alertId){return notificationCall('send-alert',{alertId})}
async function sendAllClearNotification(alertId){return notificationCall('send-all-clear',{alertId})}
function alertCard(a,admin=false){const controls=admin&&canApprove()&&a.status==='pending'?`<button class="maroon" type="button" data-approve="${a.id}">Approve & activate</button>`:'';const close=admin&&canApprove()&&['active','located'].includes(a.status)?`<button class="ghost" type="button" data-close="${a.id}">Child located / all clear</button>`:'';const remove=admin&&isAdmin()?`<button class="danger" type="button" data-delete-alert="${a.id}">Delete alert</button>`:'';const image=safeImageUrl(a.photo_url);const phone=String(a.law_phone||'').replace(/[^+\d,;#*]/g,'');return `<article class="card alert"><div class="row between"><h3>${esc(a.title||'Community Assistance Request')}</h3><span class="status ${statusClass(a.status)}">${esc(a.status)}</span></div>${image?`<img src="${esc(image)}" alt="Photo associated with this alert" loading="lazy" decoding="async" style="max-width:100%;max-height:320px;border-radius:12px">`:''}<p><strong>${esc(a.child_name||'')}</strong>${a.age?` · Age ${esc(a.age)}`:''}</p><p>${esc(a.description)}</p>${a.last_known?`<p><strong>Last known:</strong> ${esc(a.last_known)}</p>`:''}${a.vehicle?`<p><strong>Vehicle/info:</strong> ${esc(a.vehicle)}</p>`:''}${a.law_agency?`<p><strong>Investigating agency:</strong> ${esc(a.law_agency)}</p>`:''}${a.law_phone?`<p><strong>Information:</strong> <a href="tel:${esc(phone)}">${esc(a.law_phone)}</a></p>`:''}<div class="row">${controls}${close}${remove}</div></article>`}
async function loadAlerts(){
  if(alertsRequest)return alertsRequest;
  const container=$('#alerts'),button=$('#refresh');
  let succeeded=false;
  clearTimeout(refreshFeedbackTimer);
  if(button){button.disabled=true;button.textContent='Refreshing…'}
  container.setAttribute('aria-busy','true');
  alertsRequest=(async()=>{
    const {data=[],error}=await db.from('alerts').select(ALERT_COLUMNS).in('status',['active','located','closed']).order('created_at',{ascending:false}).limit(50);
    if(error)throw error;
    container.innerHTML=data.length?data.map(a=>alertCard(a)).join(''):'<div class="card"><h3>No active alerts</h3><p class="mut">There are no approved community assistance alerts right now.</p></div>';
    succeeded=true;
  })().finally(()=>{
    alertsRequest=null;
    container.removeAttribute('aria-busy');
    if(button){button.disabled=false;button.textContent=succeeded?'Up to date':'Refresh failed';refreshFeedbackTimer=setTimeout(()=>{button.textContent='Refresh alerts'},succeeded?1600:3000)}
  });
  return alertsRequest;
}
async function loadAdmin(){if(!(canApprove()||isAdmin()))return;if(adminRequest)return adminRequest;adminRequest=(async()=>{const [{data=[],error}]=await Promise.all([db.from('alerts').select(ALERT_COLUMNS).order('created_at',{ascending:false}).limit(100),isAdmin()?loadUsers(true):Promise.resolve()]);if(error)throw error;$('#pending').innerHTML=`<div class="card"><h3>District alert console</h3><p class="mut">Pending requests require an approver or administrator.</p></div>`+data.map(a=>alertCard(a,true)).join('');})().finally(()=>{adminRequest=null});return adminRequest;}
function ensureUserDirectory(){const host=$('#users');if(host.querySelector('#user-directory'))return;host.innerHTML=`<section id="user-directory" class="card"><div class="row between directory-head"><div><h3>Member directory</h3><p class="mut">Search, filter, approve, revoke, or remove member accounts.</p></div><span id="directory-count" class="directory-count">Loading…</span></div><div class="directory-tools"><label><span>Search members</span><input id="user-search" type="search" placeholder="Name" autocomplete="off"></label><label><span>Access</span><select id="user-status"><option value="all">All access</option><option value="pending">Pending</option><option value="active">Active</option><option value="revoked">Revoked</option></select></label><label><span>Role</span><select id="user-role"><option value="all">All roles</option><option value="community">Community</option><option value="creator">Creator</option><option value="approver">Approver</option><option value="admin">Admin</option></select></label></div><div id="user-rows" aria-live="polite"></div><div class="directory-footer"><button id="user-more" class="ghost hidden" type="button">Load more members</button></div></section>`;$('#user-search').addEventListener('input',e=>{clearTimeout(userDirectory.timer);userDirectory.timer=setTimeout(()=>{userDirectory.search=e.target.value.trim();loadUsers(true).catch(error=>alert(error.message))},300)});$('#user-status').addEventListener('change',e=>{userDirectory.status=e.target.value;loadUsers(true).catch(error=>alert(error.message))});$('#user-role').addEventListener('change',e=>{userDirectory.role=e.target.value;loadUsers(true).catch(error=>alert(error.message))});$('#user-more').addEventListener('click',()=>loadUsers(false).catch(error=>alert(error.message)))}
function userRow(p){const self=p.id===user.id,state=p.access_status||(p.is_active?'active':'revoked'),active=state==='active',disabled=!active||self,name=p.full_name||p.id.slice(0,8),joined=new Date(p.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});let accessButtons='';if(state==='pending')accessButtons=`<button type="button" class="maroon" data-access-decision="approve" data-user-id="${p.id}">Approve access</button><button type="button" class="danger" data-access-decision="deny" data-user-id="${p.id}">Deny access</button>`;else if(active)accessButtons=`<button type="button" class="danger" data-access-decision="revoke" data-user-id="${p.id}" ${self?'disabled title="You cannot change your own admin access here."':''}>Revoke access</button>`;else accessButtons=`<button type="button" class="maroon" data-access-decision="restore" data-user-id="${p.id}">Restore access</button>${!self?`<button type="button" class="danger" data-remove-user="${p.id}">Remove permanently</button>`:''}`;return `<div class="row between user-row" data-user-row="${p.id}"><div class="user-info"><strong>${esc(name)}</strong><span class="user-meta">Joined ${esc(joined)} · ${esc(p.role)}</span><span class="user-state ${esc(state)}">${esc(state)}</span></div><div class="row user-actions"><select aria-label="Role for ${esc(name)}" data-role="${p.id}" ${disabled?'disabled':''}><option ${p.role==='community'?'selected':''}>community</option><option ${p.role==='creator'?'selected':''}>creator</option><option ${p.role==='approver'?'selected':''}>approver</option><option ${p.role==='admin'?'selected':''}>admin</option></select><button type="button" class="ghost" data-save-role="${p.id}" ${disabled?'disabled':''}>Save role</button>${accessButtons}</div></div>`}
async function loadUsers(reset=true){ensureUserDirectory();if(userDirectory.busy)return;userDirectory.busy=true;const more=$('#user-more');more.disabled=true;if(reset){userDirectory.cursor=null;userDirectory.loaded=0;$('#user-rows').innerHTML='<div class="directory-empty">Loading members…</div>'}try{let query=db.from('profiles').select('id,full_name,role,is_active,access_status,created_at',reset?{count:'exact'}:{}).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(USER_PAGE_SIZE);if(userDirectory.search)query=query.ilike('full_name',`%${userDirectory.search}%`);if(userDirectory.status!=='all')query=query.eq('access_status',userDirectory.status);if(userDirectory.role!=='all')query=query.eq('role',userDirectory.role);if(userDirectory.cursor)query=query.or(`created_at.lt.${userDirectory.cursor.createdAt},and(created_at.eq.${userDirectory.cursor.createdAt},id.lt.${userDirectory.cursor.id})`);const {data=[],count,error}=await query;if(error)throw error;if(reset){userDirectory.total=count||0;$('#user-rows').innerHTML=''}if(data.length){$('#user-rows').insertAdjacentHTML('beforeend',data.map(userRow).join(''));userDirectory.loaded+=data.length;const last=data.at(-1);userDirectory.cursor={createdAt:last.created_at,id:last.id}}else if(reset)$('#user-rows').innerHTML='<div class="directory-empty">No members match these filters.</div>';$('#directory-count').textContent=`${userDirectory.loaded} of ${userDirectory.total}`;more.classList.toggle('hidden',data.length<USER_PAGE_SIZE||userDirectory.loaded>=userDirectory.total)}finally{userDirectory.busy=false;more.disabled=false}}
async function createAlert(e){e.preventDefault();const form=e.currentTarget,button=form.querySelector('button[type="submit"]');if(button.disabled)return;button.disabled=true;const original=button.textContent;const sendNow=canApprove();button.textContent=sendNow?'Sending alert…':'Submitting…';try{const f=new FormData(form),payload=Object.fromEntries([...f.entries()].map(([k,v])=>[k,String(v).trim()||null]));payload.title='Community Assistance Request';payload.created_by=user.id;payload.status=sendNow?'active':'pending';payload.is_public=sendNow;if(sendNow){payload.approved_by=user.id;payload.approved_at=new Date().toISOString()}const {data,error}=await db.from('alerts').insert(payload).select('id').single();if(error)return alert(error.message);form.reset();if(sendNow){try{const result=await sendAlertNotification(data.id);const delivered=Number(result.delivered||0),failed=Number(result.failed||0);alert(delivered?`Alert sent. Notifications delivered to ${delivered} device${delivered===1?'':'s'}${failed?`, with ${failed} failed.`:'.'}`:'Alert sent, but no notification devices are subscribed yet. Have each phone open the app and tap Enable notifications.')}catch(notificationError){alert(`The alert is active, but push delivery could not start: ${notificationError.message}`)}}else alert('Submitted for approval.');await Promise.all([loadAdmin(),loadAlerts()]);}finally{button.disabled=false;button.textContent=original}}
async function approve(id,button){if(button.disabled)return;button.disabled=true;const {data,error}=await db.from('alerts').update({status:'active',is_public:true,approved_by:user.id,approved_at:new Date().toISOString()}).eq('id',id).eq('status','pending').select('id').maybeSingle();if(error){button.disabled=false;return alert(error.message)}if(data)try{const result=await sendAlertNotification(id);const delivered=Number(result.delivered||0),failed=Number(result.failed||0);alert(delivered?`Alert approved and sent. Notifications delivered to ${delivered} device${delivered===1?'':'s'}${failed?`, with ${failed} failed.`:'.'}`:'Alert approved, but no notification devices are subscribed yet. Have each phone open the app and tap Enable notifications.')}catch(notificationError){alert(`The alert is active, but push delivery could not start: ${notificationError.message}`)}await Promise.all([loadAdmin(),loadAlerts()]);}
async function closeAlert(id,button){if(button.disabled)return;button.disabled=true;const {data,error}=await db.from('alerts').update({status:'closed',is_public:true,closed_at:new Date().toISOString()}).eq('id',id).in('status',['active','located']).select('id').maybeSingle();if(error){button.disabled=false;return alert(error.message)}if(data)try{await sendAllClearNotification(id)}catch(notificationError){alert(`The alert was cleared, but all-clear push delivery could not start: ${notificationError.message}`)}await Promise.all([loadAdmin(),loadAlerts()]);}
async function deleteAlert(id,button){if(button.disabled)return;const card=button.closest('.alert'),name=card?.querySelector('h3')?.textContent||'this alert';if(!confirm(`Permanently delete ${name}? This removes the alert and its notification history. This cannot be undone.`))return;button.disabled=true;button.textContent='Deleting…';const {data,error}=await db.functions.invoke('delete-alert',{body:{alertId:id}});if(error||!data?.ok){button.disabled=false;button.textContent='Delete alert';return alert(await edgeError(error,data?.error||'Alert could not be deleted.'))}await Promise.all([loadAdmin(),loadAlerts()]);}
async function saveRole(id,button){if(id===user.id)return alert('You cannot change your own admin role from this screen.');const select=document.querySelector(`[data-role="${id}"]`),original=button.textContent;button.disabled=true;button.textContent='Saving…';const {error}=await db.from('profiles').update({role:select.value}).eq('id',id);if(error){button.disabled=false;button.textContent=original;return alert(error.message)}button.textContent='Saved';setTimeout(()=>{button.disabled=false;button.textContent=original},1200);}
async function decideAccess(id,decision,button){if(id===user.id)return alert('You cannot change your own admin access from this screen.');const name=button.closest('[data-user-row]')?.querySelector('.user-info strong')?.textContent||'this member',verbs={approve:'approve',deny:'deny',revoke:'revoke access for',restore:'restore access for'};if(!confirm(`Are you sure you want to ${verbs[decision]} ${name}?`))return;button.disabled=true;const original=button.textContent;button.textContent='Saving…';try{const result=await notificationCall('access-decision',{userId:id,decision});await loadUsers(true);if(result.notificationError||result.failed)alert(`Access was updated, but one or more device notifications could not be delivered.`);else if(result.delivered>0)alert(`Access updated. ${name} was notified on ${result.delivered} device${result.delivered===1?'':'s'}.`)}catch(error){button.disabled=false;button.textContent=original;alert(error.message)}}
async function removeUser(id,button){if(id===user.id)return alert('You cannot remove your own account from this screen.');const name=button.closest('[data-user-row]')?.querySelector('.user-info strong')?.textContent||'this member';if(!confirm(`Permanently remove ${name}? Their sign-in and profile will be deleted. Existing alert records will remain without a member identity. This cannot be undone.`))return;button.disabled=true;button.textContent='Removing…';const {data,error}=await db.functions.invoke('remove-member',{body:{userId:id}});if(error||!data?.ok){button.disabled=false;button.textContent='Remove permanently';return alert(await edgeError(error,data?.error||'Member could not be removed.'))}await loadUsers(true);}
async function verifyAccess(){if(!user||Date.now()-lastAccessCheck<15000)return;if(accessCheck)return accessCheck;lastAccessCheck=Date.now();accessCheck=(async()=>{const {data,error}=await db.from('profiles').select('is_active,access_status').eq('id',user.id).single();if(error){console.warn('Could not refresh account status.',error.message);return}if(data?.is_active!==profile.is_active||data?.access_status!==profile.access_status)location.reload();})().finally(()=>{accessCheck=null});return accessCheck;}
async function boot(){console.log(`BSD #7 Community Assistance v${APP_VERSION}`);const versionEl=$('#app-version');if(versionEl)versionEl.textContent=`v${APP_VERSION}`;const {data:{session},error}=await db.auth.getSession();if(error)throw error;if(!session)return;user=session.user;try{await loadProfile()}catch(e){await db.auth.signOut({scope:'local'}).catch(()=>{});return note(e.message)}if(!profile.is_active||profile.access_status!=='active'){showAccessState();return}$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');paintIdentity();setView(routeView(),{historyMode:'replace'});navigationReady=true;await Promise.all([loadAlerts(),paintNotificationToggle().catch(error=>console.warn(error.message))]);}
$('#google').onclick=signInGoogle;$('#auth-login-tab').onclick=()=>setAuthMode('login');$('#auth-signup-tab').onclick=()=>setAuthMode('signup');$('#login-form').onsubmit=signInEmail;$('#signup-form').onsubmit=signUpEmail;$('#forgot-password').onclick=forgotPassword;$('#signout').onclick=signOut;$('#access-signout').onclick=signOut;$('#refresh').onclick=()=>loadAlerts().catch(e=>alert(e.message));$('#notify-toggle').onclick=toggleNotifications;$('#decision-notify-toggle').onclick=toggleNotifications;$('#alert-form').onsubmit=createAlert;$('#tab-feed').onclick=()=>setView('feed');$('#tab-create').onclick=()=>setView('create');$('#tab-admin').onclick=()=>setView('admin');$('.tabs').addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();moveTabFocus(1)}else if(e.key==='ArrowLeft'){e.preventDefault();moveTabFocus(-1)}else if(e.key==='Home'){e.preventDefault();setView(allowedViews()[0]);$('#tab-'+currentView)?.focus()}else if(e.key==='End'){e.preventDefault();const views=allowedViews();setView(views.at(-1));$('#tab-'+currentView)?.focus()}});window.addEventListener('popstate',()=>{if(navigationReady)setView(routeView(),{historyMode:'replace',restoreScroll:true})});window.addEventListener('hashchange',()=>{if(navigationReady&&routeView()!==currentView)setView(routeView(),{historyMode:'replace',restoreScroll:true})});document.addEventListener('click',e=>{const reset=e.target.closest('[data-reset-app]');if(reset)return resetPhoneSetup();const a=e.target.closest('[data-approve]');if(a)approve(a.dataset.approve,a);const c=e.target.closest('[data-close]');if(c)closeAlert(c.dataset.close,c);const z=e.target.closest('[data-delete-alert]');if(z)deleteAlert(z.dataset.deleteAlert,z);const r=e.target.closest('[data-save-role]');if(r)saveRole(r.dataset.saveRole,r);const x=e.target.closest('[data-access-decision]');if(x)decideAccess(x.dataset.userId,x.dataset.accessDecision,x);const d=e.target.closest('[data-remove-user]');if(d)removeUser(d.dataset.removeUser,d)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)verifyAccess().catch(()=>{})});window.addEventListener('focus',()=>verifyAccess().catch(()=>{}));db.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN'&&!user)boot();});boot().catch(e=>{console.error(e);note(e.message)});
